export { default as Home } from './pages/Home';
export { default as Login } from './pages/Login'
export { default as Signup } from './pages/Signup'
export { default as Dashboard } from './pages/Dashboard'
export { default as Profile } from './pages/Profile'
export { default as Attendance } from './pages/Attendance'
export { default as Faculty } from './pages/Faculty'
export { default as Fees } from './pages/Fees'
export { default as PayOnline } from './pages/PayOnline'
export { default as Assignment } from './pages/Assignment'
export { default as TimeTable } from './pages/TimeTable'
export { default as Quiz } from './pages/Quiz'
export { default as Result } from './pages/Result'
export { default as Datesheet } from './pages/Datesheet'
export { default as Doubt } from './pages/Doubt'
export { default as Application } from './pages/Application'
export { default as Gallery } from './pages/Gallery'
export { default as ChangePassword } from './pages/ChangePassword'
export { default as Events } from './pages/Events'
export { default as Notificationview } from './pages/Notificationview'
export { default as Support } from './pages/Support'
export { default as EventDetail } from './pages/EventDetail'
export { default as QuizSubject } from './pages/QuizSubject'
export { default as QuizList } from './pages/QuizList'
export { default as QuizModel } from './pages/QuizModel'
export { default as QuizCourse } from './pages/QuizCourse'
export { default as Spinner } from './pages/Spinner';
export { default as Holiday } from './pages/Holiday'
export { default as Profilenew } from './pages/Profilenew'
export { default as MyChild } from './pages/MyChild'
export { default as Notification } from './pages/Notification';
export { default as KidsResults } from './pages/KidsResults';
export { default as KidsResultsTable } from './pages/KidsResultsTable';
export { default as TotalAttendance } from './pages/TotalAttendance';
export { default as SubmitAssignment } from './pages/SubmitAssignment';

